ARG VARIANT=bullseye
ARG BASE_REGISTRY=ghcr.io/go-debos/test-containers
ARG BASE_IMAGE=fakemachine-${VARIANT}
ARG BASE_TAG=main
FROM $BASE_REGISTRY/$BASE_IMAGE:$BASE_TAG

ARG DEBIAN_FRONTEND=noninteractive

# Bits needed to run debos test suite
RUN apt-get update  && \
    apt-get install --no-install-recommends -y \
      unzip

# Bits needed to build debos
RUN apt-get update  && \
    apt-get install --no-install-recommends -y \
      libostree-dev

