ARG BASE_REGISTRY=ghcr.io/go-debos/test-containers
ARG BASE_IMAGE=fakemachine-arch
ARG BASE_TAG=main
FROM $BASE_REGISTRY/$BASE_IMAGE:$BASE_TAG

# Bits needed to run debos test suite
RUN pacman -Syu --noconfirm dpkg \
                            unzip \
    && find /var/cache/pacman/pkg -mindepth 1 -delete

# Bits needed to build debos
RUN pacman -Syu --noconfirm ostree \
    && find /var/cache/pacman/pkg -mindepth 1 -delete
